[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Kyle Wigley <9877221+kwigley@users.noreply.github.com>"]
edition = "2021"
default-run = "advent_of_code"
publish = false

[dependencies]
pico-args = "0.5.0"
regex = "1.7.0"
